INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (14, '2021-05-12', 'PAGAMENTO INSTANTÂNEO (PIX)', 'PIX', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (15, '2021-05-12', 'DEPÓSITO BANCÁRIO', 'DEP', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (16, '2021-05-12', 'TRANSFERÊNCIA BANCÁRIA', 'TRA', 1);

COMMIT WORK;