INSERT INTO EMP_ICMS (ICM_ID, ICM_DTCAD, ICM_NOME, ICM_ALQT, ICM_FKCST_ID_CONTRIBUINTE, ICM_FKCST_ID_CONSUMIDOR, ICM_FKCST_ID_COBRAICMSPORST, ICM_FKCST_ID_TRANSFDEPFECHADO) VALUES (10, '21-MAR-2023', 'ICMS NORMAL', 19, 1, 1, 1, 1);

COMMIT WORK;

SET TERM ^ ;

update emp_produto p
set p.prd_fkicm_id = '10'
where p.prd_fkicm_id = '5'

^
SET TERM; ^


COMMIT WORK;





