ALTER TABLE FIN_TITAR DROP CONSTRAINT  FK_TAR_FKDOC_ID;
COMMIT WORK;

ALTER TABLE FIN_TITAR_BX DROP CONSTRAINT FK_TARBX_FKDOC_ID;
COMMIT WORK;

ALTER TABLE FIN_TITAR_HIST DROP CONSTRAINT FK_TARH_FKDOC_ID;
COMMIT WORK;

DELETE FROM FIN_DOCTIPO;
COMMIT WORK;

ALTER SEQUENCE GEN_FIN_DOCTIPO RESTART WITH 0;
COMMIT WORK;

INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (1, '2018-08-01', 'NÃO INFORMADO', 'NI', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (2, '2018-08-01', 'N. FISCAL', 'NF', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (3, '2018-08-01', 'DUPLICATA', 'DUP', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (4, '2018-08-01', 'PROMISSÓRIA', 'PRO', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (5, '2018-08-01', 'CARTÃO', 'CRT', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (6, '2018-08-01', 'CHEQUE', 'CHQ', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (7, '2018-08-01', 'RECIBO', 'REC', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (8, '2018-08-01', 'CARNET', 'CRN', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (9, '2018-08-01', 'PEDIDO', 'PED', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (10, '2018-08-01', 'DINHEIRO', 'DIN', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (11, '2018-08-01', 'DESCONTO (CUSTÓDIA)', 'OPD', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (12, '2018-08-01', 'BORDERÔ', 'OPB', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (13, '2018-07-10', 'BOLETO BANCÁRIO', 'BOL', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (14, '2021-05-12', 'PAGAMENTO INSTANTÂNEO (PIX)', 'PIX', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (15, '2021-05-12', 'DEPÓSITO BANCÁRIO', 'DEP', 1);
INSERT INTO FIN_DOCTIPO (DOC_ID, DOC_DTCAD, DOC_NOME, DOC_APELIDO, DOC_FKSIT_ID) VALUES (16, '2021-05-12', 'TRANSFERÊNCIA BANCÁRIA', 'TRA', 1);

COMMIT WORK;

ALTER SEQUENCE GEN_FIN_DOCTIPO RESTART WITH 16;
COMMIT WORK;

ALTER TABLE FIN_TITAR ADD CONSTRAINT FK_TAR_FKDOC_ID FOREIGN KEY (TAR_FKDOC_ID)
REFERENCES FIN_DOCTIPO(DOC_ID)
USING INDEX FK_TAR_FKDOC_ID;
COMMIT WORK;

ALTER TABLE FIN_TITAR_BX ADD CONSTRAINT FK_TARBX_FKDOC_ID FOREIGN KEY (TARBX_FKDOC_ID)
REFERENCES FIN_DOCTIPO(DOC_ID)
USING INDEX FK_TARBX_FKDOC_ID;
COMMIT WORK;

ALTER TABLE FIN_TITAR_HIST ADD CONSTRAINT FK_TARH_FKDOC_ID FOREIGN KEY (TARH_FKDOC_ID)
REFERENCES FIN_DOCTIPO(DOC_ID)
USING INDEX FK_TARH_FKDOC_ID;
COMMIT WORK;














